# Generated by Django 4.2.20 on 2025-04-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultsubjectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('questions', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('result', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='resultcoursemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('questions', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('result', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.usermodel')),
            ],
        ),
    ]
