# Generated by Django 4.2.20 on 2025-04-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_resultsubjectmodel_resultcoursemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='subjects',
            field=models.ManyToManyField(to='examapp.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='applycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.usermodel')),
            ],
        ),
    ]
